// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=pokemoninteam
//

// Package pokemoninteam is a generated GoMock package.
package pokemoninteam

import (
	context "context"
	reflect "reflect"

	pokemoninteam "github.com/Fairuzzzzz/pokedex-api/internal/models/pokemoninteam"
	poke "github.com/Fairuzzzzz/pokedex-api/internal/repository/poke"
	gomock "go.uber.org/mock/gomock"
)

// MockpokemonOutbound is a mock of pokemonOutbound interface.
type MockpokemonOutbound struct {
	ctrl     *gomock.Controller
	recorder *MockpokemonOutboundMockRecorder
	isgomock struct{}
}

// MockpokemonOutboundMockRecorder is the mock recorder for MockpokemonOutbound.
type MockpokemonOutboundMockRecorder struct {
	mock *MockpokemonOutbound
}

// NewMockpokemonOutbound creates a new mock instance.
func NewMockpokemonOutbound(ctrl *gomock.Controller) *MockpokemonOutbound {
	mock := &MockpokemonOutbound{ctrl: ctrl}
	mock.recorder = &MockpokemonOutboundMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpokemonOutbound) EXPECT() *MockpokemonOutboundMockRecorder {
	return m.recorder
}

// SearchPokemon mocks base method.
func (m *MockpokemonOutbound) SearchPokemon(ctx context.Context, name string) (*poke.Pokemon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPokemon", ctx, name)
	ret0, _ := ret[0].(*poke.Pokemon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPokemon indicates an expected call of SearchPokemon.
func (mr *MockpokemonOutboundMockRecorder) SearchPokemon(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPokemon", reflect.TypeOf((*MockpokemonOutbound)(nil).SearchPokemon), ctx, name)
}

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockrepository) Create(ctx context.Context, model pokemoninteam.PokemonNameInTeam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockrepositoryMockRecorder) Create(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockrepository)(nil).Create), ctx, model)
}

// DeletePokemon mocks base method.
func (m *Mockrepository) DeletePokemon(ctx context.Context, teamID uint, pokemonID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePokemon", ctx, teamID, pokemonID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePokemon indicates an expected call of DeletePokemon.
func (mr *MockrepositoryMockRecorder) DeletePokemon(ctx, teamID, pokemonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePokemon", reflect.TypeOf((*Mockrepository)(nil).DeletePokemon), ctx, teamID, pokemonID)
}

// GetPokemonCount mocks base method.
func (m *Mockrepository) GetPokemonCount(ctx context.Context, teamID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPokemonCount", ctx, teamID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPokemonCount indicates an expected call of GetPokemonCount.
func (mr *MockrepositoryMockRecorder) GetPokemonCount(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPokemonCount", reflect.TypeOf((*Mockrepository)(nil).GetPokemonCount), ctx, teamID)
}

// List mocks base method.
func (m *Mockrepository) List(ctx context.Context, teamID uint) ([]pokemoninteam.PokemonTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, teamID)
	ret0, _ := ret[0].([]pokemoninteam.PokemonTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockrepositoryMockRecorder) List(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockrepository)(nil).List), ctx, teamID)
}
