version: "3"
services:
  db:
    image: postgres:latest
    container_name: local-postgres-fairuz
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pokedex

    volumes:
      - /home/fairuz/GoLanguage/postgres/
